### ISSUE TITLE
是否有完整的代码

### ISSUE THREAD

**Issue by Lexlum** [YangXuanyi/Multi-Agent-GPT#5]
web.py 中提及了gradio_multimodalchatbot，代码中未有涉及。

**Comment by YangXuanyi** [comment]
这个目前就是最完整的代码（当然，有一些功能还在开发中），您提到的gradio_multimodalchatbot，已经是一个开发好的第三方库： `from gradio_multimodalchatbot import MultimodalChatbot`

在本项目中，主要利用gradio_multimodalchatbot实现一个可以多模态输入和输出的web界面，具体演示效果可以看readme中的视频。其中，可实现多模态交互的模型或者agent是需要自己添加的。目前项目中采用agent+API的方式实现多模态交互。

**Comment by Lexlum** [comment]
十分感谢！！
